name: Build and Release on Tag

on:
  push:
    tags:
      - 'v*'  # Matches tags like v1.0.0, v2.3.4

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: crx-to-xpi_linux
            binary_name: crx-to-xpi
            release_name: crx-to-xpi-linux
            installer_file: install-linux-x64
          - os: macos-latest
            artifact_name: crx-to-xpi_darwin
            binary_name: crx-to-xpi
            release_name: crx-to-xpi-darwin
            installer_file: install-darwin-universal
          - os: windows-latest
            artifact_name: crx-to-xpi_win32
            binary_name: crx-to-xpi.exe
            release_name: crx-to-xpi-win32.exe
            installer_file: install-win-x64.exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies (mac/linux)
      if: matrix.os != 'windows-latest'
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Install dependencies (win)
      if: matrix.os == 'windows-latest'
      run: |
        python -m venv venv
        venv\Scripts\activate.ps1
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller (mac)
      if: matrix.os == 'macos-latest'
      run: |
        source venv/bin/activate
        pyinstaller --onefile --target-architecture universal2 crx-to-xpi.py
        pyinstaller --onefile --target-architecture universal2 install.py

    - name: Build with PyInstaller (linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        source venv/bin/activate
        pyinstaller --onefile crx-to-xpi.py
        pyinstaller --onefile install.py

    - name: Build with PyInstaller (win)
      if: matrix.os == 'windows-latest'
      run: |
        venv\Scripts\activate.ps1
        pyinstaller --onefile crx-to-xpi.py
        pyinstaller --onefile install.py

    - name: Rename binary (linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cp dist/crx-to-xpi dist/crx-to-xpi-linux
        cp dist/install dist/install-linux-x64

    - name: Rename binary (mac)
      if: matrix.os == 'macos-latest'
      run: |
        cp dist/crx-to-xpi dist/crx-to-xpi-darwin
        cp dist/install dist/install-darwin-universal

    - name: Rename binary (win)
      if: matrix.os == 'windows-latest'
      run: |
        Copy-Item dist/crx-to-xpi.exe dist/crx-to-xpi-win32.exe
        Copy-Item dist/install.exe dist/install-win-x64.exe
    
    - name: Package extension
      if: matrix.os == 'ubuntu-latest'
      run: |
        zip -r dist/crx-to-xpi.xpi extension/

    - name: Upload binary artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: |
          dist/${{ matrix.release_name }}
          dist/${{ matrix.installer_file }}
          dist/crx-to-xpi.xpi

  create-release:
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./artifacts/crx-to-xpi_linux/crx-to-xpi-linux
          ./artifacts/crx-to-xpi_linux/install-linux-x64
          ./artifacts/crx-to-xpi_darwin/crx-to-xpi-darwin
          ./artifacts/crx-to-xpi_darwin/install-darwin-universal
          ./artifacts/crx-to-xpi_win32/crx-to-xpi-win32.exe
          ./artifacts/crx-to-xpi_win32/install-win-x64.exe
          ./artifacts/crx-to-xpi_linux/crx-to-xpi.xpi
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}